<<<<<<< HEAD
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLVLApag7wvaXT-aJr_XN32zoW7dXPJ8',
    appId: '1:632998768428:web:a822bd22f30a41f2398689',
    messagingSenderId: '632998768428',
    projectId: 'spotit-lk',
    authDomain: 'spotit-lk.firebaseapp.com',
    storageBucket: 'spotit-lk.firebasestorage.app',
    measurementId: 'G-H692SF4DS0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBen7CO4Vg9EjTXaJD2MUhi1cBjrzmHO3Q',
    appId: '1:632998768428:ios:348d59fc03b2b8a9398689',
    messagingSenderId: '632998768428',
    projectId: 'spotit-lk',
    storageBucket: 'spotit-lk.firebasestorage.app',
    iosClientId: '632998768428-kk213kq0sfp5bli6kr152s4jj710eosd.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotit',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBen7CO4Vg9EjTXaJD2MUhi1cBjrzmHO3Q',
    appId: '1:632998768428:ios:348d59fc03b2b8a9398689',
    messagingSenderId: '632998768428',
    projectId: 'spotit-lk',
    storageBucket: 'spotit-lk.firebasestorage.app',
    iosClientId: '632998768428-kk213kq0sfp5bli6kr152s4jj710eosd.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotit',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC1tkRlLVOOK_v96YBIXDRogErrB4aYfg',
    appId: '1:632998768428:android:e9f3e2dadb379be5398689',
    messagingSenderId: '632998768428',
    projectId: 'spotit-lk',
    storageBucket: 'spotit-lk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClLVLApag7wvaXT-aJr_XN32zoW7dXPJ8',
    appId: '1:632998768428:web:b2add3b1487ee924398689',
    messagingSenderId: '632998768428',
    projectId: 'spotit-lk',
    authDomain: 'spotit-lk.firebaseapp.com',
    storageBucket: 'spotit-lk.firebasestorage.app',
    measurementId: 'G-GS51RVCCVZ',
  );

}
=======
// firebase_options.dart
//
// NOTE: Firebase backend is intentionally excluded for GUI testing.
// This file is a placeholder — the real configuration will be generated
// by `flutterfire configure` when backend work begins.
//
// Do NOT import this file until Firebase packages are restored to pubspec.yaml.
>>>>>>> a2273dd3a72b26e61d482033ab992eee3b7afd05
