import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// This file is AUTO-GENERATED by the FlutterFire CLI.
// Command to regenerate: flutterfire configure
//
// It contains Firebase project connection settings for each platform.
// Different platforms (Android, iOS, Web) each get their own set of keys
// because Firebase registers them as separate apps within the same project.
//
// DO NOT commit this file to a public repository — the API keys are sensitive.
class DefaultFirebaseOptions {

  // Returns the correct FirebaseOptions for whatever platform the app is running on.
  // Called once at startup inside Firebase.initializeApp().
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // running in a browser (Flutter Web)
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // running on an Android phone
      case TargetPlatform.iOS:
        // iOS is not yet configured — run "flutterfire configure" for iOS support
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        // Any other platform (Windows, Linux, macOS) is also not supported
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase config for the Flutter Web app.
  // These values come from the Firebase Console → Project Settings → Web app.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4MOqgwYBFikqSkWjzAnU8WQ8yF4TyBbU',
    appId: '1:632998768428:web:0cd09c5d3373f157398689',
    messagingSenderId: '632998768428', // used by Firebase Cloud Messaging (FCM)
    projectId: 'spotit-lk',
    authDomain: 'spotit-lk.firebaseapp.com',
    databaseURL:
        'https://spotit-lk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotit-lk.firebasestorage.app',
    measurementId: 'G-9N3TWBE7QY', // for Firebase Analytics
  );

  // Firebase config for the Android app.
  // These values come from google-services.json (Firebase Console → Android app).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfQLJypsV4YO69W9DSCwpzTVKB6SCaitI',
    appId: '1:632998768428:android:c6caf76989a18501398689',
    messagingSenderId: '632998768428',
    projectId: 'spotit-lk',
    databaseURL:
        'https://spotit-lk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotit-lk.firebasestorage.app',
  );
}
